set nocompatible
let mapleader = ","

source ~/.vim/etc/plugins.vim "run plugins manager Vundle
source ~/.vim/etc/filetypes.vim " Manual filetype setting
source ~/.vim/etc/functions.vim " Function definitions
source ~/.vim/etc/mapping.vim " All keybinding not related to plugins
source ~/.vim/etc/env.vim " Some path's and project settings
source ~/.vim/etc/interface.vim " Editor interface behavior and look

syntax on
set synmaxcol=300
set omnifunc=syntaxcomplete#Complete " Enable omnicompletion
set nobackup " Turn permanent backup off
set writebackup " Create backup files for no saved buffers, then remove them on save
set noswapfile
set expandtab " Use spaces instead of tabs
" set noexpandtab " Use tabs
set smarttab " Be smart when using tabs ;)
set shiftwidth=2 " 1 tab == 2 spaces
set tabstop=2
set linebreak " Line break on 500 characters
set textwidth=500
set autoindent " Auto indent
set smartindent " Smart indent
set nowrap "Wrap lines
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<

" Return to last edit position when opening files
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif

" Delete trailing white space on save
autocmd BufWrite *.css :call DeleteTrailingWS()
autocmd BufWrite *.less :call DeleteTrailingWS()
autocmd BufWrite *.py :call DeleteTrailingWS()
autocmd BufWrite *.php :call DeleteTrailingWS()
autocmd BufWrite *.coffee :call DeleteTrailingWS()
autocmd BufWrite *.markdown :call DeleteTrailingWS()

set hlsearch " turn on search highlight
set incsearch " search while typing
set ignorecase
set smartcase
set iskeyword-=- " remove '-' (dash) from being a part of a keyword in source code
set iskeyword-=$ " remove '$' from being a part of a keyword in source code

set complete+=k " Set completion to also dictionary
" File type specific dictionaries
autocmd FileType * execute 'setlocal dict+=~/.vim/dict/'.&filetype.'.dict'

" autocmd CursorMovedI * call PlaySound()
